name: 🧪 Test PHP changes

on:
  workflow_dispatch:

jobs:
  test:
    name: "PHP tests: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          - mw: 'REL1_43'
            php: 8.3
            coverage: xdebug
            experimental: false
          - mw: 'master'
            php: 8.4
            coverage: none
            experimental: true

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage }}
          extensions: mbstring, intl
          tools: composer

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v4
        with:
          path: |
            mediawiki
            !mediawiki/extensions/
            !mediawiki/vendor/
            mediawiki/phpunit.xml.dist
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}-v24

      - name: Cache Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - uses: actions/checkout@v4
        with:
          path: EarlyCopy

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        working-directory: ~
        run: bash EarlyCopy/.github/workflows/installWiki.sh ${{ matrix.mw }}

      - uses: actions/checkout@v4
        with:
          path: mediawiki/skins/Citizen

      - name: Install dependencies with Composer
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run tests with PHPUnit
        if: ${{ matrix.coverage == 'none' }}
        run: composer phpunit:entrypoint -- skins/Citizen

      - name: Run tests with PHPUnit with coverage
        if: ${{ matrix.coverage == 'xdebug' }}
        run: |
          composer phpunit:coverage-edit -- skins/Citizen
          XDEBUG_MODE=coverage composer phpunit -- --testsuite skins --coverage-clover skins/Citizen/coverage/php/coverage.xml skins/Citizen/tests/phpunit --exclude-group Stub

      - name: Scan with SonarQube
        uses: sonarsource/sonarqube-scan-action@v5
        # Only one once
        if: ${{ matrix.coverage == 'xdebug' }}
        with:
          projectBaseDir: mediawiki/skins/Citizen
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
